name: t1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.13.0
  firebase_auth: ^4.8.1  # Added for Firebase Authentication
  cloud_firestore: ^4.17.5  # Retained from your original file

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Updated for recommended linting rules

flutter:
  uses-material-design: true
