// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbdgeAKoZ7SwOxI-4k1PtXpN9oryxUJg',
    appId: '1:311478724937:web:2a068afad6af18c2ee5298',
    messagingSenderId: '311478724937',
    projectId: 'flutterauthapp-834ea',
    authDomain: 'flutterauthapp-834ea.firebaseapp.com',
    storageBucket: 'flutterauthapp-834ea.firebasestorage.app',
    measurementId: 'G-CK372G9QDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqLJnd7nNBq8WNJiLHoseOFo0fWleucAs',
    appId: '1:311478724937:android:98ad8e4a0695bc78ee5298',
    messagingSenderId: '311478724937',
    projectId: 'flutterauthapp-834ea',
    storageBucket: 'flutterauthapp-834ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE36AR_JYt9wJyuXC2XCdVSNPlYqw155Q',
    appId: '1:311478724937:ios:27f331cd737abce4ee5298',
    messagingSenderId: '311478724937',
    projectId: 'flutterauthapp-834ea',
    storageBucket: 'flutterauthapp-834ea.firebasestorage.app',
    iosBundleId: 'com.example.t1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE36AR_JYt9wJyuXC2XCdVSNPlYqw155Q',
    appId: '1:311478724937:ios:27f331cd737abce4ee5298',
    messagingSenderId: '311478724937',
    projectId: 'flutterauthapp-834ea',
    storageBucket: 'flutterauthapp-834ea.firebasestorage.app',
    iosBundleId: 'com.example.t1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVbdgeAKoZ7SwOxI-4k1PtXpN9oryxUJg',
    appId: '1:311478724937:web:c9cce7a7b350f752ee5298',
    messagingSenderId: '311478724937',
    projectId: 'flutterauthapp-834ea',
    authDomain: 'flutterauthapp-834ea.firebaseapp.com',
    storageBucket: 'flutterauthapp-834ea.firebasestorage.app',
    measurementId: 'G-VNRQRSDFXJ',
  );
}
